#!/bin/bash
set -eo pipefail

. update-functions.sh

file=README.md
dockerfile_url='https://github.com/openhab/openhab-docker/blob/master/${version}/amd64/debian/Dockerfile'
generated_content_marker="<!-- Generated by update.sh -->"

generate_version_list() {
	for version in $(build_versions)
	do
		url=$(eval "echo $dockerfile_url")
		case $version in
		2.*.M*)
			echo "* \`$version\` Experimental openHAB $version Milestone version ([Dockerfile]($url))"
			;;
		2.*-snapshot)
			echo "* \`$version\` Experimental openHAB $(echo $version | sed 's/-snapshot/ SNAPSHOT/g') version ([Dockerfile]($url))"
			;;
		*)
			echo "* \`$version\` Stable openHAB $version version ([Dockerfile]($url))"
			;;
		esac
	done
}

update_version_list() {
	copy_line="true"
	while IFS= read -r line
	do
		if [ "$line" == "$generated_content_marker" ]; then
			echo "$line"
			if [ "$copy_line" == "false" ]; then
				copy_line="true"
			else
				copy_line="false"
				generate_version_list
			fi
		elif [ "$copy_line" == "true" ]; then
			echo "$line"
		fi
	done < $file > $file.new && mv $file.new $file
}

update_last_stable_version() {
	sed -i "s#openhab/openhab:[0-9]*\.[0-9]*\.[0-9]*#openhab/openhab:$(last_stable_version)#g" $file
}

echo -n "Writing $file... "

update_version_list
update_last_stable_version

echo "done"
